## Project Part I & II
rawdata <- read.table("C://Users//zhoug//Downloads//CDI.txt")
colnames(rawdata)
mydata <- rawdata[,c("V5", "V8", "V9", "V12", "V15", "V16", "V17")]
colnames(mydata) <- c("population", "beds", "physicians", "degree", "capita_in", "income", "region")
head(mydata)

predictors <- c("population", "beds", "physicians", "degree", "capita_in", "income", "region")
i = 1




## Project 1.43 a)
model1_1 <- lm(physicians ~ population, data = mydata)
model1_2 <- lm(physicians ~ beds, data = mydata)
model1_3 <- lm(physicians ~ income, data = mydata)

sm1 = summary(model1_1)
sm2 = summary(model1_2)
sm3 = summary(model1_3)

sm1$coefficients
sm2$coefficients
sm3$coefficients

## estimated function (physicians ~ population): Y = 0.0035X + 78.1231
## estimated function (physicians ~ beds): Y = 1.2157X + 257.5505
## estimated function (physicians ~ income): Y = 0.1603X + 197.4375


## Project 1.43 b)
Y <- mydata[,c("physicians")]
X <- mydata[,c("population")]
plot(X, Y, xlab = 'Total population', ylab = 'Number of active physicians', main = 'Physicians vs Population')
abline(model1_1, col = "red")

Y <- mydata[,c("physicians")]
X <- mydata[,c("beds")]
plot(X, Y, xlab = 'Number of hospital beds', ylab = 'Number of active physicians', main = 'Physicians vs Beds')
abline(model1_2, col = "red")

Y <- mydata[,c("physicians")]
X <- mydata[,c("income")]
plot(X, Y, xlab = 'Total personal income', ylab = 'Number of active physicians', main = 'Physicians vs Income')
abline(model1_3, col = "red")

## They three all appear to have good fit of linear regression relation.


## Project 1.43 c)
MSE1 = mean(sm1$residuals^2)
MSE2 = mean(sm2$residuals^2)
MSE3 = mean(sm3$residuals^2)

MSE1
MSE2
MSE3

## The numbers of hospital beds has the smallest variability around the fitted regression line




##Project 1.44 a)
region1 <- mydata[which(mydata$region=='1'), c(4,5)]
region2 <- mydata[which(mydata$region=='2'), c(4,5)]
region3 <- mydata[which(mydata$region=='3'), c(4,5)]
region4 <- mydata[which(mydata$region=='4'), c(4,5)]

sum1 = summary(lm(capita_in ~ degree, data = region1))
sum2 = summary(lm(capita_in ~ degree, data = region2))
sum3 = summary(lm(capita_in ~ degree, data = region3))
sum4 = summary(lm(capita_in ~ degree, data = region4))

sum1$coefficient
sum2$coefficient
sum3$coefficient
sum4$coefficient

## estimated function (region1): Y = 522.16X + 9223.82
## estimated function (region2): Y = 238.67X + 13581.41
## estimated function (region3): Y = 330.61X + 10529.79
## estimated function (region4): Y = 440.32X + 8615.05


## Project 1.44 b)

## The functions are similar for the four regions. (*Extension Needed)


## Project 1.44 c)
mse1 = mean(sum1$residuals^2)
mse2 = mean(sum2$residuals^2)
mse3 = mean(sum3$residuals^2)
mse4 = mean(sum4$residuals^2)

mse1
mse2
mse3
mse4

## MSE are approximately the same for three regions except for the geographic region 2, its MSE is smaller than the three other ones.




## Project 2.62
summary(model1_1)$r.square
summary(model1_2)$r.square
summary(model1_3)$r.square

## Base on r square result of three terms, the numbers of beds has the largest reduction in variability in the numbers of active physicians.